[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++14
build_flags = -DCONFIG_BT_NIMBLE_USE_ESP_TIMER=0
lib_deps =
    tbekas/BLE-Gamepad-Client@^0.12.1
    h2zero/NimBLE-Arduino@^2.3.2
